Algoritmo "Meu primeiro algoritmo!"
// Disciplina   : Linguagem e Lógica de Programação
// Professor   : Estía
// Descrição   : Objetivo de aprender algoritmo e lógica de programação
// Autor(a)    : Elisângela Fátima Kuchamnski
// Data atual  : 13/04/2020
Var
// Seção de Declarações das variáveis 
   nota: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   nota <- 100
   escreva ("Sua nota é: ", nota)

Fimalgoritmo